# Generated by Django 2.1.1 on 2018-11-01 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, default='android', max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('appName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'AppName',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnvList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('db_config', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'EnvList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('up_time', models.CharField(blank=True, default=datetime.datetime.now, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('req_query', models.TextField(blank=True, null=True)),
                ('req_body_form', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'InterfaceList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCasesList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('up_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('parameter', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'TestCasesList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCasesResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=True)),
                ('errorInfo', models.CharField(blank=True, default='none', max_length=300, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('timeOfDuration', models.TimeField(blank=True, null=True)),
                ('runner', models.CharField(blank=True, max_length=50, null=True)),
                ('InterfaceResult', models.CharField(blank=True, max_length=100, null=True)),
                ('InterfaceStatusCodeResult', models.CharField(blank=True, max_length=10, null=True)),
                ('SqlResult', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TestCasesResult',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCasesSetList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testCases', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('showToAll', models.BooleanField(default=True)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'TestCasesSetList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TestResource',
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Token',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiTestCasesList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(blank=True, max_length=300, null=True)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
                ('steps', models.CharField(blank=True, max_length=500, null=True)),
                ('beginSteps', models.CharField(blank=True, max_length=500, null=True)),
                ('endSteps', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('showToAll', models.BooleanField(default=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'UiTestCasesList',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiTestCasesSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('testCasesId', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('showToAll', models.BooleanField(default=True)),
                ('describe', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'UiTestCasesSet',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiTestResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=True)),
                ('errorInfo', models.CharField(blank=True, default='none', max_length=300, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('timeOfDuration', models.TimeField(blank=True, null=True)),
                ('runner', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UiTestResults',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emails', models.EmailField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('avatar', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
